@startuml
class Experience {
    id
    entity
    position
    description
    startDate
    endDate
    skills
    ---
    inProgress()
    addSkill(newSkill)
    removeSkill(index)
}

class Education {
    id
    title
    description
    institution
    startDate
    endDate
    degree
    skills
    ---
    inProgress()
    addSkill(newSkill)
    removeSkill(index)
}

class Project {
    id
    title
    description
    link
    status
    skills
    ---
    changeStatus()
    inProgress()
    completed()
    addSkill(newSkill)
    removeSkill(index)
}

class Skill {
    title
    description
    area
    ---
}

Experience "1" *-- "*" Skill : skills
Education "1" *-- "*" Skill : skills
Project "1" *-- "*" Skill : skills
@enduml
